title = "Home"
baseURL = "https://greengypsy.github.io/my-favourite-things/"
languageCode = "en-us"
googleAnalytics = "G-8YKC23ZR15"
theme = "ananke"
ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["taxonomy"]
[taxonomies]
    category = "categories"
    tags = "tags"
[params]
    custom_css = ["_code.css","_styles.css"]
    background_color_class = "bg-green"
    logo = "android-chrome-512x512.png"